# device/elephone/u3h/BoardConfig.mk

# Arquitectura
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a73

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a53

# Plataforma (MediaTek MT6771/P70)
TARGET_BOARD_PLATFORM := mt6771
TARGET_BOOTLOADER_BOARD_NAME := mt6771

# Kernel (lo configuraremos después)
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x14f88000
BOARD_TAGS_OFFSET := 0x13f88000

# TWRP básico
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_INPUT_BLACKLIST := "hbtp_vm"

# Particiones y FStab
TARGET_NO_RECOVERY := false
TARGET_NO_SEPARATE_RECOVERY := true
TARGET_RECOVERY_FSTAB := device/elephone/u3h/twrp.fstab
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"

# Kernel (Generalmente para MT6771)
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x04000000
BOARD_TAGS_OFFSET := 0x00000100
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --kernel_offset $(BOARD_KERNEL_OFFSET) --ramdisk_offset $(BOARD_RAMDISK_OFFSET) --tags_offset $(BOARD_TAGS_OFFSET) --pagesize $(BOARD_KERNEL_PAGESIZE)

# Device Tree (Crucial)
# Como tienes un dtbo.img separado, configuramos esto:
BOARD_USES_GENERIC_DTB := false
BOARD_KERNEL_SEPARATED_DTBO := true
BOARD_DTB_OFFSET := 0x01000000
BOARD_BOOTIMG_HEADER_VERSION := 2

# TWRP
TW_THEME := portrait_hdpi
RECOVERY_SDCARD_ON_DATA := true
TW_EXCLUDE_APEX := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_HAS_MTP := true
TW_BRIGHTNESS_PATH := "/sys/class/backlight/panel0-backlight/brightness"
TW_MAX_BRIGHTNESS := 2047
TW_DEFAULT_BRIGHTNESS := 1200
TW_STATUSBAR_HEIGHT := 90
TW_USE_MODEL_INFO_FOR_DEVICE_ID := true
TWRP_INCLUDE_LOGCAT := true

# Encryption (Clave para resolver tu problema)
TW_CRYPTO_FS_EXT4_WRITE_SUPPORT := true
TW_CRYPTO_FS_FBE_ALLOW_VERIFY := true
TW_INCLUDE_CRYPTO := true
TWRP_RECOVERY_KEYMASTER_VERSION := 4
