#
# Copyright (C) 2022 The Android Open Source Project
#
# SPDX-License-Identifier: Apache-2.0
#

# Arquitectura
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a73
TARGET_CPU_VARIANT_RECOVERY := cortex-a73

# Chipset MediaTek
BOARD_USES_MTK_HARDWARE := true
BOARD_HAS_MTK_FM_RADIO := false
MTK_INTERNAL_BOOTLOADER_SEARCH_PATH := bootloader/preloader_evb6771
BOARD_HAVE_BL2 := true

# Particiones y FStab
TARGET_NO_RECOVERY := false
TARGET_NO_SEPARATE_RECOVERY := true
TARGET_RECOVERY_FSTAB := device/elephone/u3h/twrp.fstab
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"

# Kernel
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x04000000
BOARD_TAGS_OFFSET := 0x00000100
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --kernel_offset $(BOARD_KERNEL_OFFSET) --ramdisk_offset $(BOARD_RAMDISK_OFFSET) --tags_offset $(BOARD_TAGS_OFFSET) --pagesize $(BOARD_KERNEL_PAGESIZE)

# Device Tree
BOARD_USES_GENERIC_DTB := false
BOARD_KERNEL_SEPARATED_DTBO := true
BOARD_DTB_OFFSET := 0x01000000
BOARD_BOOTIMG_HEADER_VERSION := 2

# TWRP
TW_THEME := portrait_hdpi
RECOVERY_SDCARD_ON_DATA := true
TW_EXCLUDE_APEX := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_HAS_MTP := true
TW_BRIGHTNESS_PATH := "/sys/class/backlight/panel0-backlight/brightness"
TW_MAX_BRIGHTNESS := 2047
TW_DEFAULT_BRIGHTNESS := 1200
TW_STATUSBAR_HEIGHT := 90
TW_USE_MODEL_INFO_FOR_DEVICE_ID := true
TWRP_INCLUDE_LOGCAT := true

# Encryption
TW_CRYPTO_FS_EXT4_WRITE_SUPPORT := true
TW_CRYPTO_FS_FBE_ALLOW_VERIFY := true
TW_INCLUDE_CRYPTO := true
TWRP_RECOVERY_KEYMASTER_VERSION := 4

# Producto
PRODUCT_NAME := u3h
PRODUCT_DEVICE := u3h
PRODUCT_BRAND := elephone
PRODUCT_MANUFACTURER := elephone
PRODUCT_MODEL := Elephone U3H
PRODUCT_GMS_CLIENTID_BASE := android-elephone
