name: Build TWRP Recovery - Optimized

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Device Codename'
        required: false
        default: 'u3h'
      brand:
        description: 'Device Brand' 
        required: false
        default: 'elephone'
      twrp_branch:
        description: 'TWRP Branch'
        required: false
        default: 'twrp-9.0'

env:
  DEVICE: ${{ github.event.inputs.device || 'u3h' }}
  BRAND: ${{ github.event.inputs.brand || 'elephone' }}
  TWRP_BRANCH: ${{ github.event.inputs.twrp_branch || 'twrp-10.0' }}

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/anibal/actions-runner/_work

    steps:
    - name: Clean workspace
      run: |
        echo "=== LIMPIANDO TRABAJOS ANTERIORES ==="
        rm -rf /home/anibal/actions-runner/_work/*
        mkdir -p /home/anibal/actions-runner/_work

    - name: Checkout manual
      run: |
        cd /home/anibal/actions-runner/_work
        git clone https://github.com/AnibalRa/TWRP_OFOX_PBRP_SHRP_Recovery_Builder.git
        cd TWRP_OFOX_PBRP_SHRP_Recovery_Builder
        git submodule update --init --recursive
    
    - name: Setup environment
      run: |
        echo "PATH=$PATH" >> $GITHUB_ENV
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV  
        echo "HOME=$HOME" >> $GITHUB_ENV
        echo "LC_ALL=C" >> $GITHUB_ENV
        echo "TERM=xterm" >> $GITHUB_ENV  
        
    - name: Initialize TWRP build
      run: |
        cd /home/anibal/actions-runner/_work
        echo "=== INICIANDO REPO ==="
        /home/anibal/bin/repo init -u https://github.com/mlm-games/platform_manifest_twrp_omni.git -b $TWRP_BRANCH

    - name: Add device tree to manifest
      run: |
        cd /home/anibal/actions-runner/_work
        mkdir -p .repo/local_manifests
        echo '<?xml version="1.0" encoding="UTF-8"?>' > .repo/local_manifests/roomservice.xml
        echo '<manifest>' >> .repo/local_manifests/roomservice.xml
        echo '  <project path="device/$BRAND/$DEVICE" name="AnibalRa/TWRP_OFOX_PBRP_SHRP_Recovery_Builder" remote="github" revision="main" />' >> .repo/local_manifests/roomservice.xml
        echo '</manifest>' >> .repo/local_manifests/roomservice.xml

    - name: Sync sources
      run: |
        cd /home/anibal/actions-runner/_work
        echo "=== SINCRONIZANDO REPOSITORIO ==="
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
        
    - name: Fix locale settings
      run: |
        sudo apt-get update
        sudo apt-get install -y locales
        sudo locale-gen en_US.UTF-8
        sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
        export LC_ALL=en_US.UTF-8
        export LANG=en_US.UTF-8
        
    - name: Build TWRP
      run: |
        cd /home/anibal/actions-runner/_work
        echo "=== INICIANDO COMPILACIÓN ==="
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch omni_$DEVICE-eng
        make recoveryimage -j$(nproc --all)

    - name: Capture build evidence
      if: always()
      run: |
        cd /home/anibal/actions-runner/_work
        echo "=== EVIDENCIA DE COMPILACIÓN ===" > /home/anibal/build_evidence.txt
        echo "=== ROOMSERVICE ===" >> /home/anibal/build_evidence.txt
        cat .repo/local_manifests/roomservice.xml >> /home/anibal/build_evidence.txt
        echo "=== ARCHIVOS DEVICE ===" >> /home/anibal/build_evidence.txt
        find device/ -name "*.mk" >> /home/anibal/build_evidence.txt
        echo "=== ÚLTIMOS LOGS ===" >> /home/anibal/build_evidence.txt
        tail -50 build.log >> /home/anibal/build_evidence.txt 2>/dev/null || echo "No build.log found" >> /home/anibal/build_evidence.txt
