name: Build TWRP Recovery - Optimized

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Device Codename'
        required: false
        default: 'u3h'
      brand:
        description: 'Device Brand' 
        required: false
        default: 'elephone'
      twrp_branch:
        description: 'TWRP Branch'
        required: false
        default: 'twrp-9.0'

env:
  DEVICE: ${{ github.event.inputs.device || 'u3h' }}
  BRAND: ${{ github.event.inputs.brand || 'elephone' }}
  TWRP_BRANCH: ${{ github.event.inputs.twrp_branch || 'twrp-10.0' }}

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 180

    steps:
    - name: Clean workspace
      run: |
        echo "=== LIMPIANDO TRABAJOS ANTERIORES ==="
        rm -rf /home/anibal/actions-runner/_work/*
        mkdir -p /home/anibal/actions-runner/_work

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize TWRP build
      run: |
        cd /home/anibal/actions-runner/_work
        echo "=== INICIANDO REPO ==="
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b $TWRP_BRANCH

    - name: Add device tree to manifest
      run: |
        cd /home/anibal/actions-runner/_work
        mkdir -p .repo/local_manifests
        echo '<?xml version="1.0" encoding="UTF-8"?>' > .repo/local_manifests/roomservice.xml
        echo '<manifest>' >> .repo/local_manifests/roomservice.xml
        echo '  <project path="device/$BRAND/$DEVICE" name="AnibalRa/TWRP_OFOX_PBRP_SHRP_Recovery_Builder" remote="github" revision="main" />' >> .repo/local_manifests/roomservice.xml
        echo '</manifest>' >> .repo/local_manifests/roomservice.xml

    - name: Sync sources
      run: |
        cd /home/anibal/actions-runner/_work
        echo "=== SINCRONIZANDO REPOSITORIO ==="
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Build TWRP
      run: |
        cd /home/anibal/actions-runner/_work
        echo "=== INICIANDO COMPILACIÓN ==="
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch omni_$DEVICE-eng
        make recoveryimage -j$(nproc --all)

    - name: Capture build evidence
      if: always()
      run: |
        cd /home/anibal/actions-runner/_work
        echo "=== EVIDENCIA DE COMPILACIÓN ===" > /home/anibal/build_evidence.txt
        echo "=== ROOMSERVICE ===" >> /home/anibal/build_evidence.txt
        cat .repo/local_manifests/roomservice.xml >> /home/anibal/build_evidence.txt
        echo "=== ARCHIVOS DEVICE ===" >> /home/anibal/build_evidence.txt
        find device/ -name "*.mk" >> /home/anibal/build_evidence.txt
        echo "=== ÚLTIMOS LOGS ===" >> /home/anibal/build_evidence.txt
        tail -50 build.log >> /home/anibal/build_evidence.txt 2>/dev/null || echo "No build.log found" >> /home/anibal/build_evidence.txt
